GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFuVGVzdFdvcmsiLCJpYXQiOjE3MjE4MTUyNDh9.Nq1UlOTCjQQSO7UOtD1XJUEdjT4iiiBJ1iVLhI9sdKA

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": 
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjMsInVzZXJuYW1lIjoiTWFuVGVzdFdvcmsiLCJwYXNzd29yZCI6IjEyMzQ1Njc4IiwiaWF0IjoxNzIxMjgzNzM3LCJleHAiOjE3MjEzNDM3Mzd9._g4Qq5AS5iJfJsEHc1KNbk9PUFnQapyviWvNmPldHKw"
}
###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ29ybiIsImlhdCI6MTcyMTAyNjkxM30.9JacPckXX8sKMBE2zudkyLHovqfJmQrXr0d1ZhNDg6Q"
}

### 
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "ManTestWork",
    "password": "CHECK",
    "title": "TestPost"
}
